### ISSUE TITLE
Permalink can be duplicated if two entries have the same title

### ISSUE THREAD

**Issue by sonyagreen** [resin-io/pensieve#244] opened 2017-12-22 21:22 UTC
## Expected Behavior
A permalink is unique to an entry

## Actual Behavior
A permalink is built using the title information, which can be duplicated
https://resin-io.github.io/scratchpad/?0%5Bn%5D=Full%20text%20search&0%5Bv%5D=2fa

## Steps to Reproduce the Problem

1. Create two entries with the same title text
1. Use the permalink for one of them
1. Scroll down to see second entry

**Comment by lurch** [comment] 2017-12-23 01:09
Possibly a duplicate of #235 ?

**Comment by LucianBuzzo** [comment] 2017-12-29 17:05
This will be resolved by https://github.com/resin-io/pensieve/pull/247

**Comment by lurch** [comment] 2018-01-29 10:43
i guess this can be closed now?

**Closed** 2018-01-29 10:48 UTC
